### ISSUE TITLE
Keine Multicast Verbindung zwischen Arduino und ESP8266 möglich

### ISSUE THREAD

**Issue by nobodykmd** [DynamoBen/WIFItally#3]
Hey ich habe Schwierigkeiten eine Verbindung zwischen Arduino und dem ESP zu realisieren trotz aller Modifikationen welche via Anleitung zu tätigen sind.

Haben Sie eine Idee wie man aktuell eine Verbindung realisieren kann.

Ich verwende ein Wemos D1 und ein Arduino Mega mit einem EthernetShield W5100.

**Comment by DynamoBen** [comment]
Sorry dieses projekt nicht verwenden und Arduino ist es nur um das ESP konzipiert. Ich kann Ihnen mit dem Arduino Mega oder W5100 nicht helfen.
