### ISSUE TITLE
Do not do libraries

### ISSUE THREAD

**Issue by alirezaershadmanesh** [DynamoBen/WIFItally#7]
Hello
I was compiling the program. But these libraries are not: #include <StreamString.h> and #include <FS.h> and #include <WiFiUdp.h>
Where can I find them?

**Comment by DynamoBen** [comment]
It appears that you don't have the ESP8266 board libraries installed correctly. [These instructions](https://learn.adafruit.com/adafruit-huzzah-esp8266-breakout/using-arduino-ide) may help.

**Comment by alirezaershadmanesh** [comment]
I did the same, but without the module. Of course, I have to compile the code without the module, but it does not do this.

**Comment by alirezaershadmanesh** [comment]
Hi. I copied the function fs.h. but it's still not in red. The program is
compiling, but ssdid does not appear .Please helpe me

**Comment by DynamoBen** [comment]
I can't tell from your description what the root cause of your problem is. FS.h is included at the project level and doesn't need to be copied anywhere. 

What you're experiencing appears to be a development environment setup issue. If your IDE is setup correctly and you have all the dependencies installed then the project will compile and run correctly.

**Comment by alirezaershadmanesh** [comment]
I use Arduino 1.8.6. I went through the steps, except for this line:
To upload the static files via the Arduino IDE you will need this tool:
https://github.com/esp8266/arduino-esp8266fs-plugin
Do I have to go through this line?

**Comment by DynamoBen** [comment]
> I use Arduino 1.8.6. I went through the steps, except for this line: To upload the static files via the Arduino IDE you will need this tool: https://github.com/esp8266/arduino-esp8266fs-plugin Do I have to go through this line?

The project will compile and function without this step, however the configuration webpages will not be themed correctly and look a bit odd.

**Comment by alirezaershadmanesh** [comment]
Hi, good time. Maybe a new link will send me the functions and necessary
items. Maybe I downloaded the wrong one because the link links have expired.
As atem.h   fs,h EthernetUdp.h.I just have these problems
Thank you

**Comment by alirezaershadmanesh** [comment]
Hi, I talked to an expert engineer. She saw all the software. He has
trouble-free functions fs.h. You may check the functions in a new way. And
give it a link?
I need this very much
Please give me all the functions
Thank you

**Comment by DynamoBen** [comment]
When you program your device ensure that under Tools | Flash Size that the option selected is NOT "no SPIFFS." FS needs SPIFFS to function.

**Comment by alirezaershadmanesh** [comment]
Hello i have a private message, can i say it?
