### ISSUE TITLE
How I make it work on Mac, Wirecast

### ISSUE THREAD

**Issue by mtcd00** [DynamoBen/WIFItally#8]
I saw that files are .exe so I though How do I connect the tally light to Wirecast?

**Comment by DynamoBen** [comment]
The application (.exe) runs while using Wirecast and communicates between Wirecast and the tally lights.

**Comment by mtcd00** [comment]
The exe application runs on macOS?

**Comment by DynamoBen** [comment]
Not supported on Mac

**Comment by mtcd00** [comment]
And there is no way to adapt ti mac? :( I already bought all components

**Comment by DynamoBen** [comment]
The Mac version of Wirecast uses applescript which requires code changes to this project. I do not have the hardware to make these changes. 

The project is open source and you are welcome to make those changes, or find someone else that can, and submit a PR.

**Comment by mtcd00** [comment]
I am happy to contribute to this project so others can make use of it on
macs as well. Not sure how to ask someone else to make the changes, can you
help?

**Comment by DynamoBen** [comment]
I'm not able to help with this. A developer familiar with python, Applescript, and the Wirecast API should be able to create a Mac version of this project fairly quickly. I can approve any PRs that are submitted.

**Comment by mtcd00** [comment]
Not familiar with any of these. How can I find this type of developers and
where? 🤔

**Comment by DynamoBen** [comment]
Sorry I can't help with that, and sorry this doesn't support Mac.
